# Generated by Django 3.1.2 on 2022-02-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='clean_id',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='reply',
            name='clean_id',
            field=models.TextField(default=0),
        ),
    ]
